/*global MutationObserver, CSSRule */
/**
 * @fileOverview This file contains the /components/ module for emulating Web Components behavior.
 * @name components.js<src>
 * @author Etienne Prud’homme
 * @version 1.0.0
 * @link https://github.com/notetiene/components
 * @todo Keep track of instances. This way, the style tag could be removed.
 * @license GPLv3
 */
var components=function(){function e(e){var t=document.implementation.createHTMLDocument(""),n=document.createElement("style");return n.textContent=e,t.body.appendChild(n),n.sheet.cssRules}function t(t,n){var r,o=e(t),a=null,l=n.className,c="",i=0;if(l.length<10)throw new Error("“topNode” doesn’t contain classes to act asselector or is too short & risk to have collisions");for(l="."+l.replace(" ","."),r=o.length;i<r;i++){if(a=o[i],a.type!==CSSRule.STYLE_RULE)throw new Error("Only style rules are currently supported for style scoping");c+=l+" "+a.cssText}return c}var n={},r=document.createRange();r.selectNode(document.body);var o=function(e,t,r){if(e.constructor!==String||""===e)throw new Error("Cannot register the component. The name must be a String.");if(t.constructor!==String||""===t)throw new Error("Cannot register "+e+" component. The template must be a String.");if(void 0!==n[e]&&n.hasOwnProperty(e))throw new Error(e+" is an already registered component.");var o=r||{};Object.defineProperty(n,e,{enumerable:!1,configurable:!1,writable:!1,value:{template:t,proto:o}})},a=function(e){if(!n.hasOwnProperty(e))throw new Error("“"+e+"” is not a registered component");for(var o=n[e],a=r.createContextualFragment(o.template),l=null,c=0,i=a.childNodes.length;c<i;c++)if(8!==a.childNodes[c].nodeType){l=a.childNodes[c];break}if(null===l)throw new Error("The “"+e+"” component doesn’t contain a valid node.");var s,u=e+"-components-lib-styles",d=document.getElementById(u);if(l.className=l.className+" components-lib-topNode",null===d&&(s=o.proto.style||null,"[object String]"===Object.prototype.toString.apply(s))){var p=document.createElement("style");p.id=u,p.textContent=t(s,l),document.head.appendChild(p)}var m=o.proto.createdCallback||{};m instanceof Function&&m.call(a);var h=o.proto.attachedCallback;if(h instanceof Function){var f=new MutationObserver(function(e){for(var t=0,n=e.length;t<n;t++)"childList"===e[t].type&&0===a.childNodes.length&&h.call(l)});f.observe(a,{childList:!0})}var v=o.proto.attributeChangedCallback;if(v instanceof Function){var b=new MutationObserver(function(e){for(var t=0,n=e.length;t<n;t++)"attributes"===e[t].type&&v.call(l)});b.observe(l,{attributes:!0})}return a};return{registerElement:o,createElement:a}}();